package com.example.kanjilearning.data

object KanjiDeck {
    val top100 = listOf(
        KanjiEntry("日", "にち/ひ", "day/sun", "Tag/Sonne", 4, "1→2→3→4 (outside frame before center)"),
        KanjiEntry("一", "いち", "one", "eins", 1, "single horizontal stroke"),
        KanjiEntry("国", "くに", "country", "Land", 8, "outer frame first, close frame last"),
        KanjiEntry("人", "ひと/じん", "person", "Person", 2, "left-falling then right-falling"),
        KanjiEntry("年", "ねん", "year", "Jahr", 6, "top to bottom"),
        KanjiEntry("大", "だい/おお", "big", "groß", 3, "horizontal, left slash, right slash"),
        KanjiEntry("十", "じゅう", "ten", "zehn", 2, "horizontal then vertical"),
        KanjiEntry("二", "に", "two", "zwei", 2, "top short then bottom long"),
        KanjiEntry("本", "ほん", "book/origin", "Buch/Ursprung", 5, "tree + base mark"),
        KanjiEntry("中", "なか/ちゅう", "middle", "Mitte", 4, "box then central line"),
        KanjiEntry("長", "なが/ちょう", "long", "lang", 8, "top to bottom"),
        KanjiEntry("出", "で/しゅつ", "exit", "Ausgang", 5, "upper mountain then lower"),
        KanjiEntry("三", "さん", "three", "drei", 3, "top to bottom"),
        KanjiEntry("時", "じ", "time/hour", "Zeit/Stunde", 10, "left radical first"),
        KanjiEntry("行", "い/こう", "go", "gehen", 6, "left component then right"),
        KanjiEntry("見", "み/けん", "see", "sehen", 7, "eye then legs"),
        KanjiEntry("月", "つき/げつ", "month/moon", "Monat/Mond", 4, "vertical + inner strokes"),
        KanjiEntry("後", "あと/ご", "after", "nach", 9, "left then right"),
        KanjiEntry("前", "まえ/ぜん", "before", "vor", 9, "top then bottom"),
        KanjiEntry("生", "せい/い", "life", "Leben", 5, "top to bottom"),
        KanjiEntry("五", "ご", "five", "fünf", 4, "top to bottom"),
        KanjiEntry("間", "あいだ/かん", "interval", "Zwischenraum", 12, "gate outside then sun inside"),
        KanjiEntry("上", "うえ/じょう", "up", "oben", 3, "vertical then horizontals"),
        KanjiEntry("東", "ひがし/とう", "east", "Osten", 8, "top then center"),
        KanjiEntry("四", "よん/し", "four", "vier", 5, "outer box then inside"),
        KanjiEntry("今", "いま/こん", "now", "jetzt", 4, "top cap then below"),
        KanjiEntry("金", "きん/かね", "gold/money", "Gold/Geld", 8, "top to bottom"),
        KanjiEntry("九", "きゅう/く", "nine", "neun", 2, "left hook then sweep"),
        KanjiEntry("入", "い/にゅう", "enter", "eintreten", 2, "left then right"),
        KanjiEntry("学", "がく/まな", "study", "lernen", 8, "roof then child"),
        KanjiEntry("高", "たか/こう", "high", "hoch", 10, "top then enclosure"),
        KanjiEntry("円", "えん", "yen/circle", "Yen/Kreis", 4, "outer then inner"),
        KanjiEntry("子", "こ/し", "child", "Kind", 3, "top, vertical, hook"),
        KanjiEntry("外", "そと/がい", "outside", "außen", 5, "left part then right"),
        KanjiEntry("八", "はち", "eight", "acht", 2, "left then right"),
        KanjiEntry("六", "ろく", "six", "sechs", 4, "top then bottom"),
        KanjiEntry("下", "した/か", "down", "unten", 3, "horizontal, vertical, dot"),
        KanjiEntry("来", "く/らい", "come", "kommen", 7, "top to bottom"),
        KanjiEntry("気", "き", "spirit/energy", "Geist/Energie", 6, "top radical then lower"),
        KanjiEntry("小", "ちい/しょう", "small", "klein", 3, "center then sides"),
        KanjiEntry("七", "なな/しち", "seven", "sieben", 2, "horizontal then bend"),
        KanjiEntry("山", "やま/さん", "mountain", "Berg", 3, "center then sides"),
        KanjiEntry("話", "はなし/わ", "speak", "sprechen", 13, "speech radical first"),
        KanjiEntry("女", "おんな/じょ", "woman", "Frau", 3, "left sweep, right, cross"),
        KanjiEntry("北", "きた/ほく", "north", "Norden", 5, "left then right"),
        KanjiEntry("午", "ご", "noon", "Mittag", 4, "top to bottom"),
        KanjiEntry("百", "ひゃく", "hundred", "hundert", 6, "top line first"),
        KanjiEntry("書", "か/しょ", "write", "schreiben", 10, "top to bottom"),
        KanjiEntry("先", "さき/せん", "before/ahead", "zuvor", 6, "top then legs"),
        KanjiEntry("名", "な/めい", "name", "Name", 6, "evening then mouth"),
        KanjiEntry("川", "かわ/せん", "river", "Fluss", 3, "left, middle, right"),
        KanjiEntry("千", "せん", "thousand", "tausend", 3, "top then cross"),
        KanjiEntry("水", "みず/すい", "water", "Wasser", 4, "center then sides"),
        KanjiEntry("半", "はん", "half", "Hälfte", 5, "top then bottom"),
        KanjiEntry("男", "おとこ/だん", "man", "Mann", 7, "field then power"),
        KanjiEntry("西", "にし/せい", "west", "Westen", 6, "top to bottom"),
        KanjiEntry("電", "でん", "electricity", "Elektrizität", 13, "rain then field"),
        KanjiEntry("校", "こう", "school", "Schule", 10, "tree then exchange"),
        KanjiEntry("語", "ご", "language", "Sprache", 14, "speech then five+mouth"),
        KanjiEntry("土", "つち/ど", "earth", "Erde", 3, "horizontal, vertical, base"),
        KanjiEntry("木", "き/もく", "tree", "Baum", 4, "cross then diagonals"),
        KanjiEntry("聞", "き/ぶん", "hear", "hören", 14, "gate then ear"),
        KanjiEntry("食", "た/しょく", "eat", "essen", 9, "top to bottom"),
        KanjiEntry("車", "くるま/しゃ", "car", "Auto", 7, "top to bottom"),
        KanjiEntry("何", "なに/なん", "what", "was", 7, "person radical first"),
        KanjiEntry("南", "みなみ/なん", "south", "Süden", 9, "top frame then inside"),
        KanjiEntry("万", "まん", "ten thousand", "zehntausend", 3, "horizontal then hook"),
        KanjiEntry("毎", "まい", "every", "jeder", 6, "top then mother"),
        KanjiEntry("白", "しろ/はく", "white", "weiß", 5, "box then dot"),
        KanjiEntry("天", "てん", "heaven", "Himmel", 4, "two then person"),
        KanjiEntry("母", "はは/ぼ", "mother", "Mutter", 5, "base then dots"),
        KanjiEntry("火", "ひ/か", "fire", "Feuer", 4, "left then right"),
        KanjiEntry("右", "みぎ/う", "right", "rechts", 5, "left-top then mouth"),
        KanjiEntry("読", "よ/どく", "read", "lesen", 14, "speech radical first"),
        KanjiEntry("友", "とも/ゆう", "friend", "Freund", 4, "left then right"),
        KanjiEntry("左", "ひだり/さ", "left", "links", 5, "top-left then craft"),
        KanjiEntry("休", "やす/きゅう", "rest", "ruhen", 6, "person then tree"),
        KanjiEntry("父", "ちち/ふ", "father", "Vater", 4, "top then crossing"),
        KanjiEntry("雨", "あめ/う", "rain", "Regen", 8, "frame then drops"),
        KanjiEntry("店", "みせ/てん", "shop", "Geschäft", 8, "shelter then fortune"),
        KanjiEntry("会", "あ/かい", "meet", "treffen", 6, "top then cloud"),
        KanjiEntry("駅", "えき", "station", "Bahnhof", 14, "horse radical first"),
        KanjiEntry("春", "はる/しゅん", "spring", "Frühling", 9, "three, person, sun"),
        KanjiEntry("秋", "あき/しゅう", "autumn", "Herbst", 9, "grain then fire"),
        KanjiEntry("冬", "ふゆ/とう", "winter", "Winter", 5, "top to bottom"),
        KanjiEntry("夏", "なつ/か", "summer", "Sommer", 10, "head then legs"),
        KanjiEntry("安", "やす/あん", "cheap/peaceful", "günstig/ruhig", 6, "roof then woman"),
        KanjiEntry("新", "あたら/しん", "new", "neu", 13, "stand+tree+axe"),
        KanjiEntry("古", "ふる/こ", "old", "alt", 5, "cross then mouth"),
        KanjiEntry("広", "ひろ/こう", "wide", "breit", 5, "shelter then private"),
        KanjiEntry("明", "あか/めい", "bright", "hell", 8, "sun then moon"),
        KanjiEntry("病", "やまい/びょう", "illness", "Krankheit", 10, "sickness radical first"),
        KanjiEntry("院", "いん", "institution", "Institut", 10, "mound then perfect"),
        KanjiEntry("映", "うつ/えい", "reflect", "spiegeln", 9, "sun then center"),
        KanjiEntry("映", "うつ/えい", "reflect", "spiegeln", 9, "sun then center"),
        KanjiEntry("海", "うみ/かい", "sea", "Meer", 9, "water radical then every"),
        KanjiEntry("空", "そら/くう", "sky", "Himmel", 8, "hole radical then craft"),
        KanjiEntry("道", "みち/どう", "road", "Weg", 12, "movement radical last"),
        KanjiEntry("空", "そら/くう", "sky", "Himmel", 8, "hole radical then craft"),
        KanjiEntry("花", "はな/か", "flower", "Blume", 7, "grass then transform"),
        KanjiEntry("青", "あお/せい", "blue", "blau", 8, "top then moon"),
        KanjiEntry("赤", "あか/せき", "red", "rot", 7, "earth then small"),
        KanjiEntry("黒", "くろ/こく", "black", "schwarz", 11, "field + fire dots"),
        KanjiEntry("音", "おと/おん", "sound", "Klang", 9, "stand then sun"),
        KanjiEntry("楽", "たの/がく", "music/fun", "Musik/Spaß", 13, "white+wood variant"),
        KanjiEntry("漢", "かん", "Chinese/kanji", "chinesisch/Kanji", 13, "water then right part"),
        KanjiEntry("字", "じ", "character", "Zeichen", 6, "roof then child")
    ).distinctBy { it.kanji }.take(100)
}
